server:
  port: 8285
  
spring:
  application:
    name: CONFIG-SERVER
  
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Aayush-Tiwari-NucleusTeq/microservice-config
          clone-on-start: true